/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { Following } from "./Following";
import { FollowingCountArgs } from "./FollowingCountArgs";
import { FollowingFindManyArgs } from "./FollowingFindManyArgs";
import { FollowingFindUniqueArgs } from "./FollowingFindUniqueArgs";
import { DeleteFollowingArgs } from "./DeleteFollowingArgs";
import { FollowingService } from "../following.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Following)
export class FollowingResolverBase {
  constructor(
    protected readonly service: FollowingService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Following",
    action: "read",
    possession: "any",
  })
  async _followingsMeta(
    @graphql.Args() args: FollowingCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Following])
  @nestAccessControl.UseRoles({
    resource: "Following",
    action: "read",
    possession: "any",
  })
  async followings(
    @graphql.Args() args: FollowingFindManyArgs
  ): Promise<Following[]> {
    return this.service.followings(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Following, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Following",
    action: "read",
    possession: "own",
  })
  async following(
    @graphql.Args() args: FollowingFindUniqueArgs
  ): Promise<Following | null> {
    const result = await this.service.following(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Following)
  @nestAccessControl.UseRoles({
    resource: "Following",
    action: "delete",
    possession: "any",
  })
  async deleteFollowing(
    @graphql.Args() args: DeleteFollowingArgs
  ): Promise<Following | null> {
    try {
      return await this.service.deleteFollowing(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
